### ISSUE TITLE
How to make a test on specific document ?

### ISSUE THREAD

**Issue by greatMonster11** [iwangjian/textsum-gan#22]
Hi, after follow the instruction on README file. I want to make a summarize on a single test document. 
How can I do that. Thank you.

I'm running on:
- OS: Ubuntu 20.04
- Python: 3.6.9
- Tensorflow: 1.4.1

**Comment by iwangjian** [comment]
Hi, you can view a single test document as the test set, and follow the instruction at https://github.com/abisee/cnn-dailymail to get the same format as the CNN/DailyiMail dataset. Then you can use our code to run decoding.

**Comment by greatMonster11** [comment]
Thanks @iwangjian. That would help me a lot.
