### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by PratikNalage** [iwangjian/textsum-gan#3]
I'm getting the following error

```
Traceback (most recent call last):
  File "main.py", line 210, in <module>
    tf.app.run()
  File "/home/game-of-codes/anaconda3/envs/py3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 192, in main
    generator_batcher = Batcher(FLAGS.data_path, vocab, hps, single_pass=FLAGS.single_pass)
  File "/home/game-of-codes/Work/Projects/TS Experiments/textsum-gan/batcher.py", line 250, in __init__
    self._example_queue = queue.Queue(BATCH_QUEUE_MAX * self._hps.batch_size)
TypeError: unsupported operand type(s) for *: 'int' and 'Flag'

```

**Comment by iwangjian** [comment]
Which version of tensorflow do you use? You could mandatorily convert ``hps.batch_size`` into type ``int``.

**Comment by hanyegirl** [comment]
i meet the same trouble,and then try to convert hps.batch_size into  type int by using 
int (self._hps.batch_size),but it emerges the follow error
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    tf.app.run()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "main.py", line 184, in main
    generator_batcher = Batcher(FLAGS.data_path, vocab, hps, single_pass=FLAGS.single_pass)
  File "/home/dhy/gan_for_abstractive/textsum-gan-master/batcher.py", line 250, in __init__
    self._example_queue = queue.Queue(BATCH_QUEUE_MAX * int (self._hps.batch_size))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'Flag'
then i try to solve this problem ,but have no effect,do you have any suggestions?thanks for your help

**Comment by hanyegirl** [comment]
i solve this problem by change the tensorflow version into 1.40,wish it will help you

**Comment by giriallada** [comment]
I keep getting this error in the very first step
```
`/home/giri/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/home/giri/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    tf.app.run()
  File "/home/giri/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 171, in main
    raise Exception("Problem with flags: %s" % args)
Exception: Problem with flags: ['main.py', './home/giri/Music/sumdata/finished_files/train.bin']
```
>

**Comment by iwangjian** [comment]
It's because you need some more arguments when running the ```main.py```, you can follow the examples in the ```README.md```.

**Comment by giriallada** [comment]
I followed the exact same steps given in the README.md still getting the same output

**Comment by iwangjian** [comment]
Which step did you run? Show me your complete running command?

**Comment by giriallada** [comment]
the very first step
`giri@giri-HP-Pavilion-Notebook` ~/Music/textsum-gan-master $ python3 main.py --mode=pretrain --data_path= ./home/giri/Music/sumdata/finished_files/train.bin --vocab_path=./home/giri/Music/sumdata/finished_files/vocab --log_root=./log --restore_best_model=False
/home/giri/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "main.py", line 202, in <module>
    tf.app.run()
  File "/home/giri/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 171, in main
    raise Exception("Problem with flags: %s" % args)
Exception: Problem with flags: ['main.py', './home/giri/Music/sumdata/finished_files/train.bin']
``

**Comment by iwangjian** [comment]
In your arguments ```--data_path``` and ```--vocab_path```, you want to use the absolute path but  with wrong format, they should be ```--data_path=/home/giri/Music/sumdata/finished_files/train.bin``` and ```--vocab_path=/home/giri/Music/sumdata/finished_files/vocab```, respectively.

**Comment by Forlogen** [comment]
你好，我按readme.md的命令输入python3 main.py --mode=train --data_path=my_path --vocab_apth=my_path --log_root=my_path --pretrain_dis_data_path=my_path --restore_best_model=False运行程序，但是出现了ValueError:The 'mode' flag must be one of pretrain/train/decode，请问你遇到过这种错误吗？期待您的回复~

**Comment by iwangjian** [comment]
我这里没有遇到过呃，你可以再仔细排查下呢

**Comment by HunterYCG** [comment]
To write the variables to the format like self._hps.batch_size.value

**Comment by XyzaBi** [comment]
> i solve this problem by change the tensorflow version into 1.40,wish it will help you

I also meet this problem, but there is no 1.40 of Tensorflow, are you sure?

**Comment by XyzaBi** [comment]
I have solved this problem!!
change main.py line 79 into'' for key, val in FLAGS.flag_values_dict().items(): '' for python 3
"for key, val in FLAGS.flag_values_dict().iteritems():" for python 2

**Comment by lipanpanpanpan** [comment]
我也遇到了这个问题  唉

**Comment by DEEP2907** [comment]
> type



> It's because you need some more arguments when running the `main.py`, you can follow the examples in the `README.md`.



> Which version of tensorflow do you use? You could mandatorily convert `hps.batch_size` into type `int`.

how can we convert the batch_size into type int?
