### ISSUE TITLE
我打不开dropbox链接

### ISSUE THREAD

**Issue by hanyegirl** [iwangjian/textsum-gan#5]
You can download the generated data discriminator_train_data.npz for discriminator from dropbox. Meanwhile, you can follow the instructions below to prepare negative samples by yourself.但是点击dropbox提示是无效链接，可以重新发一下链接吗

**Comment by iwangjian** [comment]
链接：https://www.dropbox.com/s/i1otqkrsgup63pt/discriminator_train_data.npz?dl=0

**Comment by hanyegirl** [comment]
谢谢，我才发现这个链接需要翻墙。。
